### PR TITLE
Adding spsur package to Spatial ctv

### PR DESCRIPTION
**Pull request by rominsal**
We have added two new lines to Spatial ctv to include spsur package. We have added also spsur package to the list of CRAN packages.

### CODE REVIEW

**Comment by rsbivand** [comment]
We cannot act on this now, I'm afraid. The whole CTV system is being revised, so it'll take some weeks at best before anything may appear. Then this repo will be closed and all issues/PRs should be made to the new repo in https://github.com/cran-task-views, as stated clearly in this repos README. I'll try to ensure that this content is included.

**Comment by zeileis** [comment]
The maintainer also suggested to add the `spsur` package to the "Econometrics" task view. What do you think Roger @rsbivand , is it worth to add the package to both views?

**Comment by rsbivand** [comment]
No, not yet. Once Spatial is stable, we should link the spatial econometrics section from the Econometrics TV, as is done already under further models. Will there be a way of tagging sections that can be used for cross-linking?

**Comment by zeileis** [comment]
Thanks, that would be good. Re-reading the section "Spatial regression" in _Spatial_ and the item "Spatial econometric models" in _Econometrics_, I think it would be good to streamline the latter with some information from the former. Do you want to suggest something in an issue, maybe? That would be great.

Re: tagging sections. (a) Currently, there is no unified intrastructure for this and it depends on the individual task views whether they create something taggable or not. (b) I wouldn't recommend to tag sections because these are more likely to become outdated as task views change (independently from each other).

**Pull request closed without merging**
