### PR TITLE
each sentence on a separate line 

### PR DESCRIPTION
**Pull request by Nowosad**
- this makes it easier to keep track of changes.
@rsbivand is this PR helpful for you?
Also - if I want to make some changes to the text, should I edit the `int/Spatial.md` or `ctv/Spatial.ctv`?

### CODE REVIEW

**Comment by rsbivand** [comment]
Thanks, I'll check this tomorrow. Changes to the `ctv` file only please; the `md` file is generated from the `ctv` file.

**Comment by Nowosad** [comment]
Aha, ok. I've edited the md file - so disregard it. I will edit the `ctv` file in the next few days.

**Comment by rsbivand** [comment]
OK, and thanks for any contributions - I agree that breaking the lines makes good sense. Maybe wait until I've processed #1 to avoid modifying the stale source files.

**Comment by rsbivand** [comment]
Have now merged #1 and made a number of edits early in the *.ctv file. Consider running `ctv::ctv2html(ctv::read.ctv("Spatial.ctv"))` to check for syntax errors, and `ctv::check_ctv_packages("Spatial.ctv")` to check that packages named in `<info>` are listed in `<packagelist>`.

**Pull request closed without merging**
